//! Build-time codegen for the rstudio/r-system-requirements rules.
//!
//! Parses every JSON rule in `vendor/r-system-requirements/rules/` and emits
//! a Rust source file (`$OUT_DIR/sysreqs_rules_generated.rs`) with static
//! tables the runtime fallback consumes. No regex compilation happens here
//! — that's done lazily on first use via `OnceLock` in the runtime module.
//!
//! The emitted shape mirrors the JSON schema but flattens `dependencies[].constraints`
//! into per-distro entries so runtime lookups are cheap filtering over a flat slice.

use serde::Deserialize;
use std::{fmt::Write as _, fs, path::PathBuf};

#[derive(Debug, Deserialize)]
struct Rule {
    patterns: Vec<String>,
    dependencies: Vec<Dependency>,
}

#[derive(Debug, Deserialize)]
struct Command {
    command: String,
}

#[derive(Debug, Deserialize)]
struct Dependency {
    packages: Vec<String>,
    #[serde(default)]
    constraints: Vec<Constraint>,
    #[serde(default)]
    pre_install: Vec<Command>,
    #[serde(default)]
    post_install: Vec<Command>,
}

#[derive(Debug, Deserialize)]
struct Constraint {
    #[serde(default)]
    os: Option<String>,
    #[serde(default)]
    distribution: Option<String>,
    #[serde(default)]
    versions: Vec<String>,
}

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let rules_dir = manifest_dir
        .join("vendor")
        .join("r-system-requirements")
        .join("rules");

    println!("cargo:rerun-if-changed={}", rules_dir.display());
    println!("cargo:rerun-if-changed=build.rs");

    let mut rules: Vec<(String, Rule)> = Vec::new();
    for entry in fs::read_dir(&rules_dir).expect("vendor/r-system-requirements/rules missing") {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("json") {
            continue;
        }
        let name = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap()
            .to_string();
        let body = fs::read_to_string(&path).unwrap();
        let rule: Rule = serde_json::from_str(&body)
            .unwrap_or_else(|e| panic!("{} failed to parse: {e}", path.display()));
        rules.push((name, rule));
    }
    rules.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str(
        "// Generated by build.rs from vendor/r-system-requirements/rules.\n\
         // Do not edit by hand.\n\n",
    );
    out.push_str("pub struct ConstraintStatic {\n    pub os: Option<&'static str>,\n    pub distribution: Option<&'static str>,\n    pub versions: &'static [&'static str],\n}\n\n");
    out.push_str("pub struct DependencyStatic {\n    pub packages: &'static [&'static str],\n    pub constraints: &'static [ConstraintStatic],\n    pub pre_install: &'static [&'static str],\n    pub post_install: &'static [&'static str],\n}\n\n");
    out.push_str("pub struct RuleStatic {\n    pub name: &'static str,\n    pub patterns: &'static [&'static str],\n    pub dependencies: &'static [DependencyStatic],\n}\n\n");
    writeln!(out, "pub static RULES: &[RuleStatic] = &[").unwrap();
    for (name, rule) in &rules {
        writeln!(out, "    RuleStatic {{").unwrap();
        writeln!(out, "        name: {:?},", name).unwrap();
        write!(out, "        patterns: &[").unwrap();
        for p in &rule.patterns {
            write!(out, "{:?}, ", p).unwrap();
        }
        writeln!(out, "],").unwrap();
        writeln!(out, "        dependencies: &[").unwrap();
        for dep in &rule.dependencies {
            writeln!(out, "            DependencyStatic {{").unwrap();
            write!(out, "                packages: &[").unwrap();
            for p in &dep.packages {
                write!(out, "{:?}, ", p).unwrap();
            }
            writeln!(out, "],").unwrap();
            writeln!(out, "                constraints: &[").unwrap();
            for c in &dep.constraints {
                write!(out, "                    ConstraintStatic {{ os: ").unwrap();
                match &c.os {
                    Some(s) => write!(out, "Some({:?})", s).unwrap(),
                    None => write!(out, "None").unwrap(),
                }
                write!(out, ", distribution: ").unwrap();
                match &c.distribution {
                    Some(s) => write!(out, "Some({:?})", s).unwrap(),
                    None => write!(out, "None").unwrap(),
                }
                write!(out, ", versions: &[").unwrap();
                for v in &c.versions {
                    write!(out, "{:?}, ", v).unwrap();
                }
                writeln!(out, "] }},").unwrap();
            }
            writeln!(out, "                ],").unwrap();
            write!(out, "                pre_install: &[").unwrap();
            for c in &dep.pre_install {
                write!(out, "{:?}, ", c.command).unwrap();
            }
            writeln!(out, "],").unwrap();
            write!(out, "                post_install: &[").unwrap();
            for c in &dep.post_install {
                write!(out, "{:?}, ", c.command).unwrap();
            }
            writeln!(out, "],").unwrap();
            writeln!(out, "            }},").unwrap();
        }
        writeln!(out, "        ],").unwrap();
        writeln!(out, "    }},").unwrap();
    }
    writeln!(out, "];").unwrap();

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("sysreqs_rules_generated.rs");
    fs::write(&out_path, out).unwrap();
}
